### ISSUE TITLE
Bring tmLanguage as up to speed as possible

### ISSUE THREAD

**Issue by princemaple** [asbjornenge/Docker.tmbundle#10]
- [x] accept escaped chars in directive args
- [ ] highlight invalid newlines without a backslash on the previous line
- [ ] _add more here..._

**Comment by asbjornenge** [comment]
@princemaple I also added a `.gitignore` for the `.cache` files. So be sure to pull :wink: 

Also, would it be a huge pain to move the `Dockerfile.sublime-syntax` into the `Syntaxes` folder? Does that noe make sense? Keeping it a bit cleaner...?

**Comment by princemaple** [comment]
> Also, would it be a huge pain to move the Dockerfile.sublime-syntax into the Syntaxes folder?

Quick testing suggests that it can be moved. :+1: I'll just need to update my `ApplySyntax` settings to point to the new location once you have moved it, I use names other than just `Dockerfile`.

**Comment by asbjornenge** [comment]
@princemaple feel free to just do both (move+update) in a branch and PR? :stuck_out_tongue: :+1: Going off the grid for a bit (kindergarden pickups etc. etc.) but will be back online this evening :smile:

**Comment by asbjornenge** [comment]
@princemaple such great work recently my friend :grin: :tada: Thanks a bunch for stepping up and helping out!

What do you think about this [linguist](https://github.com/github/linguist) repo? Should we make a PR? Or should we perhaps aspire to fix the `highlight invalid newlines without a backslash on the previous line` issue first?

Actually, if you take a look at their [grammars](https://github.com/github/linguist/tree/master/vendor/grammars) - this repo was updated as early as 9 days ago. So perhaps they have some sort of automatic update feature on new tags or something? Maybe we don't have to do anything :stuck_out_tongue_closed_eyes:

**Comment by princemaple** [comment]
Looks like they do update the grammars folder from time to time, we don't have to worry about it then.
They have this script that gets run every time travis runs, but really updating the repo seems to be a manual job, at least they update all submodules when they do.

https://github.com/github/linguist/blob/master/script/fast-submodule-update
https://github.com/github/linguist/blob/master/script/travis/before_install

**Comment by princemaple** [comment]
If we were to send a PR, it would be a simple `git submodule update ...`

**Comment by asbjornenge** [comment]
@princemaple either way is fine with me :smile:

**Comment by infininight** [comment]
There is no need to do a PR, they pull ever ~4-6 weeks and deploy to Github itself, doing a PR won't speed up this process.

**Comment by princemaple** [comment]
@infininight thanks for the information
