### ISSUE TITLE
Add support for multistage dockerfiles

### ISSUE THREAD

**Issue by wyaeld** [asbjornenge/Docker.tmbundle#15]
2 small syntax changes in 2017.05 and onwards

https://docs.docker.com/engine/userguide/eng-image/multistage-build/

AS is now a keyword
FROM can occur multiple times in the body

I looked at the code, but not familiar enough with the structure to see how to do this.

**Comment by andyneff** [comment]
Also, FROM no longer has to be the first `Dockerfile` command in the file.

**Comment by asbjornenge** [comment]
Thanks for submitting these 👍  I am a bit swamped atm. with deadlines on other projects. Would appreciate a PR if anyone kan find the time 💖  If not I'll get on it in a few weeks.
