### ISSUE TITLE
Filename Madness

### ISSUE THREAD

**Issue by jnovack** [asbjornenge/Docker.tmbundle#16]
There are many main-stream different conventions to name your dockerfile. 

I'm not here to judge, I would just like to know if the filename regex can be changed to match a broader number of Docker ... uhh ... files.

`.*[d|D]ockerfile.*`

![image](https://user-images.githubusercontent.com/387006/27958289-5dbb74e0-62f0-11e7-84ba-6b27a7ecbbea.png)

I even considered the Windows users, this will even match the `Dockerfile` at the bottom of the list.  Look how gracious I am.

At the very least, perhaps a `first_line_match: "^FROM\s\w"`?

**Comment by andyneff** [comment]
With docker 17.06, the first line no longer has to be "^FROM\s\w"

The ARG command can also come first (I'm not sure if any others can), as can a blank line or comment.

**Comment by asbjornenge** [comment]
I'm super swamped in other projects. I've listed you as a maintainer @andyneff, so feel free to just implement these changes if you find some time. You should be allowed to commit to this project directly 😄 👍

**Comment by blag** [comment]
Fixed.
