### ISSUE TITLE
Dockerfile `AS` keyword not highlighted

### ISSUE THREAD

**Issue by XVilka** [asbjornenge/Docker.tmbundle#30]
It is used in a FROM construction to alias the name:
```Dockerfile
FROM alpine:edge AS builder
```
See https://docs.docker.com/engine/reference/builder/#from for the reference.

![image](https://user-images.githubusercontent.com/203261/63162387-fadbb780-c054-11e9-8c6a-349dbd6925d4.png)

See https://github.com/github/linguist/issues/4612

**Comment by blag** [comment]
Duplicate of #15. Closing.
