### ISSUE TITLE
Earthly support

### ISSUE THREAD

**Issue by zedtux** [asbjornenge/Docker.tmbundle#32]
[Earthly](https://www.earthly.dev) is a kind of `Makefile` to build `Dockerfile`s so that you declare a file like this:

```dockerfile
FROM ruby
WORKDIR /app

deps:
    RUN apt-update \
        apt-install --yes git

    SAVE IMAGE

docker:
    FROM +deps

    RUN git --version

    SAVE IMAGE docker:git
```

and using the `earth` command line tool, it will build the final image:

```
earth +docker
```

_The example I'm giving make no sens but I wanted to keep it very simple._

Have a look at [their Basics documentation](https://docs.earthly.dev/guides/basics) for better examples.

Using this package in order to highlight a `Earthfile` is already well working but needs some improvements:

* Obviously, this package should support `Earthfile` in addition to `Dockerfile`.
* The _targets_ (`deps` and `docker` in my example) should be coloured. I was thinking of a blue color.
* [The Earthly specific commands](https://docs.earthly.dev/earthfile), like `SAVE IMAGE`, `SAVE ARTIFACT` and so on needs to be coloured like `RUN`, `COPY` and so on.
* The `FROM` command is not coloured when having spaces in front of it and it should in a `Earthfile`

Please see here what I have right now:

![Screenshot 2020-09-30 at 08 20 39](https://user-images.githubusercontent.com/478564/94649985-1c9a0b80-02f6-11eb-915e-afd4bf15ad03.png)

**Comment by vladaionescu** [comment]
This is being developed at a separate plugin in the end: https://github.com/earthly/earthly/issues/331. I believe this issue can be closed.
