### ISSUE TITLE
Half of the coloring missing

### ISSUE THREAD

**Issue by Seluj78** [asbjornenge/Docker.tmbundle#33]
Hi!
I was looking at this dockerfile and the color is incorrect for half the file

https://github.com/sickcodes/Docker-OSX/blob/8343da16fc3f2c5ebc6e1f79dbf53cdf3639d1f8/Dockerfile#L116-L198

cheers

**Comment by rwbarton** [comment]
It looks like the syntax highlighting thinks that the sequence `\'` can be used to quote a `'` character in the middle of a single-quoted string, but this isn't actually true; this backslash is just a backslash. This occurs three times on lines 116, 117, 118, so from line 118 onward, the syntax highlighting has the insides and outsides of single-quoted strings swapped.

**Comment by sickcodes** [comment]
Here's the explanation if you're wondering why:
https://www.gnu.org/software/bash/manual/html_node/Single-Quotes.html

```bash
echo '\'
\
```
```bash
echo $'\'
>
```
```bash
echo $"\"
>
```
```bash
echo "\"
>
```

**Comment by princemaple** [comment]
Hi, checkout the latest `Dockerfile (with Bash)` syntax

![image](https://user-images.githubusercontent.com/1329716/147161542-2f64b6d5-d8ea-4fe7-8275-11703011824e.png)

**Comment by sickcodes** [comment]
I also noticed Sublime text now offers Dockerfile (with Bash), so I assume the above is the same solution.

Perhaps allow or permit some type of `LABEL syntax=bash` vs. `LABEL syntax=sh`, if at all possible, or recognise `SHELL ["/bin/bash", "-c"]`, if this helps.
