### ISSUE TITLE
Mailing list archive text files recognized as Dockerfile

### ISSUE THREAD

**Issue by dnicolson** [asbjornenge/Docker.tmbundle#34]
Mailing list archives begin with the text `From ` which apparently causes them to be identified as the type Dockerfile even though they have a `.txt` file extension.

Here is an example from the [file mailing list](https://mailman.astron.com/pipermail/file/2018-November.txt.gz):
<img width="648" alt="Screen Shot 2021-03-21 at 16 04 14" src="https://user-images.githubusercontent.com/2276355/111909946-8d2d1400-8a5f-11eb-8893-1baf2d27a4c2.png">

**Comment by princemaple** [comment]
Hi, this is caused by the firstline match guessing. You can force it to display in other syntax with https://packagecontrol.io/packages/ApplySyntax
