### ISSUE TITLE
Dockerfile with bash misses some bash commands

### ISSUE THREAD

**Issue by alison985** [asbjornenge/Docker.tmbundle#41]
```
RUN apt update && \
apt-get install -y vim
```
will only highlight the second line as bash. But `apt update && \` is also bash and is not highlighted.

**Comment by princemaple** [comment]
I cannot reproduce the error. However I got the opposite behavior and it's expected:

![image](https://github.com/asbjornenge/Docker.tmbundle/assets/1329716/525ef466-55db-406b-93cd-a17f42ed5d0b)

To fix this, simply indent the second line:

![image](https://github.com/asbjornenge/Docker.tmbundle/assets/1329716/083e2ab8-d989-4ea2-83c8-d9bbdce15c15)

**Comment by alison985** [comment]
Indent, got it. Thank you!
