### ISSUE TITLE
Only highlights if first line is `FROM` directive

### ISSUE THREAD

**Issue by znxftw** [asbjornenge/Docker.tmbundle#45]
Hi there! Went down a bit of a rabbit hole to reach here to find the root cause of an issue I was facing - needed some understanding on how this package works and what is expected.

[zola](https://github.com/getzola/zola) uses this theme to highlight markdown text in dockerfiles.

I noticed when writing codeblocks that if I wanted to show a snippet of a dockerfile - e.g. only the `RUN` command, it wasn't getting highlighted.

So to try and find the root cause, I reached here - I've never really used Sublime before this but installed it and got this package to test out.

Looks like even if I explicitly set the file type in Sublime to be 'Dockerfile' it doesn't recognise the syntax until I add a 'FROM' directive (I'm aware that Dockerfile itself has the restriction that the first line needs to be FROM, but does that require the highlighting to also slip away?)

<img width="501" alt="image" src="https://github.com/user-attachments/assets/b4e5f8b3-babe-4284-9eba-7a1fe1dee2f3">
<img width="502" alt="image" src="https://github.com/user-attachments/assets/3ca1354b-f6de-4cb2-840c-d8fbe10eb967">

Is this the expectation? If I named my file Dockerfile (or atleast set the language on the bottom right corner), shouldn't it automatically highlight any and all syntax? Have I misconfigured something? Quite new to the whole world of `sublime-syntax` so bear with me a bit if this is a silly question!

**Comment by princemaple** [comment]
It is expected. A valid Dockerfile starts with one of the followings:
1. comment
2. ARG
3. FROM
